tasks:
  - name: player-service-app setup
    init: |
      cd player-service-app
      pip install -r requirements.txt
  - name: player-service-model setup
    before: |
      cd player-service-model
      docker build -t a4a_model .
    init: docker run -d -p 5000:5000 a4a_model
  - name: llm-setup
    before: |
      docker pull ollama/ollama
      docker run -d -v ollama:/root/.ollama -p 11434:11434 --name ollama ollama/ollama
    init: docker exec -it ollama ollama run tinyllama


ports:
  - port: 5000
    onOpen: open-preview
  - port: 8000
    onOpen: open-preview